version: 2

updates:
  # Monitor GitHub Actions versions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies

  # Monitor Docker base image
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
